CREATE TABLE `jubensha_booking` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `unique_no` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '唯一值',
  `user_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '用户 openid',
  `user_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '用户名称',
  `booking_time` datetime DEFAULT NULL COMMENT '开本时间',
  `store_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '店名或区域',
  `script_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '剧本名称',
  `script_details` text COLLATE utf8mb4_unicode_ci COMMENT '详情说明',
  `discount_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '正常' COMMENT '优惠类型：正常、低价、折扣、免单',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
  `is_api` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否可靠/官方来源',
  `wechat_no` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '微信号',
  `booking_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'group' COMMENT '信息类型：group组局，seek_group求组',
  `is_completed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否完成：0未完成，1已完成',
  `province_id` int(11) DEFAULT NULL COMMENT '省份ID',
  `province_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '省份名称',
  `city_id` int(11) DEFAULT NULL COMMENT '城市ID',
  `city_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市名称',
  `district_id` int(11) DEFAULT NULL COMMENT '区县ID',
  `district_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '区县名称',
  PRIMARY KEY (`id`),
  KEY `jubensha_booking_user_id_index` (`user_id`),
  KEY `jubensha_booking_booking_time_index` (`booking_time`),
  KEY `jubensha_booking_expire_time_index` (`expire_time`),
  KEY `jubensha_booking_booking_type_index` (`booking_type`),
  KEY `jubensha_booking_is_api_index` (`is_api`),
  KEY `jubensha_booking_unique_no_index` (`unique_no`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jubensha_all_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `unique_no` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '唯一值',
  `sender_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '发送者名称',
  `sender_wx_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发送者的微信id',
  `content` text COLLATE utf8mb4_unicode_ci,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_unique_no` (`unique_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='剧本杀所有内容';
